//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextGen.Properties.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можливо знайти шлях до файлу. Спочатку відкрийте файл з завданням.
        /// </summary>
        internal static string CantFindDefPath {
            get {
                return ResourceManager.GetString("CantFindDefPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можливо знайти шлях до файлу. Спочатку відкрийте файл з завданням. Після цього можна зберегти файл з іншою назвою.
        /// </summary>
        internal static string CantFindDefPath2 {
            get {
                return ResourceManager.GetString("CantFindDefPath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спочатку виберіть файл і згенеруйте його!.
        /// </summary>
        internal static string ChouseFileFst {
            get {
                return ResourceManager.GetString("ChouseFileFst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування завантажені.
        /// </summary>
        internal static string DefLoaded {
            get {
                return ResourceManager.GetString("DefLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генеруємо... Зачекайте, будь ласка.
        /// </summary>
        internal static string Gen {
            get {
                return ResourceManager.GetString("Gen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML не було збережено автоматично. Виберіть файл з завданням або виберіть папку для &quot;index.html&quot;.
        /// </summary>
        internal static string HtmlNotAutoSaved {
            get {
                return ResourceManager.GetString("HtmlNotAutoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML збережено.
        /// </summary>
        internal static string HtmlSaved {
            get {
                return ResourceManager.GetString("HtmlSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст збережено.
        /// </summary>
        internal static string TextSaved {
            get {
                return ResourceManager.GetString("TextSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст занадто короткий. Це точно тести?.
        /// </summary>
        internal static string TextToShort {
            get {
                return ResourceManager.GetString("TextToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секунду, рендеримо...
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
    }
}
