//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AppStartingPrealoader {
            get {
                object obj = ResourceManager.GetObject("AppStartingPrealoader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v4.0.0-alpha.6 (https://getbootstrap.com)
        /// * Copyright 2011-2017 The Bootstrap Authors
        /// * Copyright 2011-2017 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v5.0.0 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,footer,header,nav,section{display:block}h1{font-size:2em;margin:.67em 0}figcaption,fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_min {
            get {
                return ResourceManager.GetString("bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можливо знайти шлях до файлу. Спочатку відкрийте файл з завданням.
        /// </summary>
        internal static string CantFindDefPath {
            get {
                return ResourceManager.GetString("CantFindDefPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можливо знайти шлях до файлу. Спочатку відкрийте файл з завданням. Після цього можна зберегти файл з іншою назвою.
        /// </summary>
        internal static string CantFindDefPath2 {
            get {
                return ResourceManager.GetString("CantFindDefPath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спочатку виберіть файл і згенеруйте його!.
        /// </summary>
        internal static string ChouseFileFst {
            get {
                return ResourceManager.GetString("ChouseFileFst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування завантажені.
        /// </summary>
        internal static string DefLoaded {
            get {
                return ResourceManager.GetString("DefLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///    var tour = new Shepherd.Tour({
        ///        defaults: {
        ///            classes: &apos;shepherd-theme-arrows&apos;
        ///        }
        ///    });
        ///
        ///
        ///    tour.addStep(&apos;st-1&apos;, {
        ///        title: &apos;Hi!&apos;,
        ///        text: &apos;I will show you some simple steps in generating content&apos;,
        ///
        ///        buttons: [{
        ///            text: &apos;No, thanks&apos;,
        ///            action: tour.cancel
        ///        }, {
        ///            text: &apos;Let`s start!&apos;,
        ///            action: tour.next
        ///            }]
        ///    });
        ///    tour.addStep(&apos;st-4&apos;, {
        ///        title: &apos;Settin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string easy_start_tour_EN {
            get {
                return ResourceManager.GetString("easy_start_tour_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function ()
        ///{    
        ///    var tour = new Shepherd.Tour({
        ///            defaults: {
        ///                classes: &apos;shepherd-theme-arrows&apos;
        ///            }
        ///        });
        ///
        ///
        ///        tour.addStep(&apos;st-1&apos;, {
        ///            title: &apos;Привіт!&apos;,
        ///            text: &apos;Я покажу Вам декілька простих кроків з генератором&apos;,
        ///
        ///            buttons: [{
        ///            text: &apos;Ні, дякую&apos;,
        ///            action: tour.cancel
        ///        },{
        ///                text: &apos;Продовжимо&apos;,
        ///                action: tour.next
        ///            }]
        ///        });
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string easy_start_tour_UA {
            get {
                return ResourceManager.GetString("easy_start_tour_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon1 {
            get {
                object obj = ResourceManager.GetObject("favicon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// *  Font Awesome 4.7.0 by @davegandy - http://fontawesome.io - @fontawesome
        /// *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
        /// */@font-face{font-family:&apos;FontAwesome&apos;;src:url(&apos;../fonts/fontawesome-webfont.eot?v=4.7.0&apos;);src:url(&apos;../fonts/fontawesome-webfont.eot?#iefix&amp;v=4.7.0&apos;) format(&apos;embedded-opentype&apos;),url(&apos;../fonts/fontawesome-webfont.woff2?v=4.7.0&apos;) format(&apos;woff2&apos;),url(&apos;../fonts/fontawesome-webfont.woff?v=4.7.0&apos;) format(&apos;woff&apos;),url(&apos;../fonts/fontawesome-webfont.ttf?v=4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string font_awesome_min {
            get {
                return ResourceManager.GetString("font_awesome_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генеруємо... Зачекайте, будь ласка.
        /// </summary>
        internal static string Gen {
            get {
                return ResourceManager.GetString("Gen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML не було збережено автоматично. Виберіть файл з завданням або виберіть папку для &quot;index.html&quot;.
        /// </summary>
        internal static string HtmlNotAutoSaved {
            get {
                return ResourceManager.GetString("HtmlNotAutoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML збережено.
        /// </summary>
        internal static string HtmlSaved {
            get {
                return ResourceManager.GetString("HtmlSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; src=&quot;./content/favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///
        ///    &lt;link href=&quot;./content/css/shepherd-theme-arrows.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;./content/css/style.css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;./content/css/bootstrap.min.css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;./content/css/tether.min.css&quot;&gt;
        ///    &lt;link rel=&quot;style [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v3.2.1 | (c) JS Foundation and other contributors | jquery.org/license */
        ///!function(a,b){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){&quot;use strict&quot;;var c=[],d=a.document,e=Object.getPrototypeOf,f=c.slice,g=c.concat,h=c.push,i=c.indexOf,j={},k=j.toString,l=j.hasOwnProperty,m=l.toStrin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_3_2_1_min {
            get {
                return ResourceManager.GetString("jquery_3_2_1_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery UI - v1.12.1 - 2016-09-14
        ///* http://jqueryui.com
        ///* Includes: core.css, accordion.css, autocomplete.css, menu.css, button.css, controlgroup.css, checkboxradio.css, datepicker.css, dialog.css, draggable.css, resizable.css, progressbar.css, selectable.css, selectmenu.css, slider.css, sortable.css, spinner.css, tabs.css, tooltip.css, theme.css
        ///* To view and modify this theme, visit http://jqueryui.com/themeroller/?bgShadowXPos=&amp;bgOverlayXPos=&amp;bgErrorXPos=&amp;bgHighlightXPos=&amp;bgContentXPos=&amp;bgHeaderXPos=&amp; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_ui_min {
            get {
                return ResourceManager.GetString("jquery_ui_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(&apos;#loc-file-drop&apos;).text(&apos;Файл&apos;);
        ///$(&apos;#loc-prefs-drop&apos;).text(&apos;Налаштування&apos;);
        ///$(&apos;#loc-about&apos;).text(&apos;Про програму&apos;);
        ///$(&apos;#loc-open&apos;).text(&apos;Відкрити файл&apos;);
        ///$(&apos;#loc-txt-s&apos;).text(&apos;Зберегти&apos;);
        ///$(&apos;#loc-txt-ss&apos;).text(&apos;Зберегти як&apos;);
        ///$(&apos;#loc-html-s&apos;).text(&apos;Зберегти&apos;);
        ///$(&apos;#loc-html-ss&apos;).text(&apos;Зберегти як&apos;);
        ///$(&apos;#loc-exit&apos;).text(&apos;Вихід&apos;);
        ///$(&apos;#loc-prefs&apos;).text(&apos;Вигляд&apos;);
        ///$(&apos;#loc-sett&apos;).text(&apos;Налаштування&apos;);
        ///$(&apos;#loc-gend&apos;).text(&apos;Згенероване&apos;);
        ///$(&apos;#loc-txt-from&apos;).text(&apos;Текст з файлу&apos;);
        ///$(&apos;#loc-gen&apos;).text(&apos;Ген [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string localize_UA {
            get {
                return ResourceManager.GetString("localize_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Copyright Marc J. Schmidt. See the LICENSE file at the top-level
        /// * directory of this distribution and at
        /// * https://github.com/marcj/css-element-queries/blob/master/LICENSE.
        /// */
        ///;
        ///(function (root, factory) {
        ///    if (typeof define === &quot;function&quot; &amp;&amp; define.amd) {
        ///        define(factory);
        ///    } else if (typeof exports === &quot;object&quot;) {
        ///        module.exports = factory();
        ///    } else {
        ///        root.ResizeSensor = factory();
        ///    }
        ///}(this, function () {
        ///
        ///    // Make sure it does not throw in a SSR (Server Si [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResizeSensor {
            get {
                return ResourceManager.GetString("ResizeSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    // background-image: url(img/back1.png);
        ///    background-repeat: no-repeat;
        ///    background-size: cover;
        ///    height: 100vh;
        ///    background-position: center;
        ///    padding: 0;
        ///    font-size: 1em;
        ///    min-width: 280px;
        ///    overflow: hidden;
        ///    background-color: antiquewhite;
        ///    -webkit-user-select: none;
        ///}
        ///
        ///body * {
        ///    cursor: url(../cursors/arrow.cur), pointer;
        ///}
        ///
        ///textarea {
        ///    cursor: url(../cursors/text.cur), text;
        ///}
        ///
        ///body::after {
        ///    content: &quot;&quot;;
        ///    background: url(img [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tether-element,.tether-element *,.tether-element :after,.tether-element :before,.tether-element:after,.tether-element:before{box-sizing:border-box}.tether-element{position:absolute;display:none}.tether-element.tether-open{display:block}.
        /// </summary>
        internal static string tether_min {
            get {
                return ResourceManager.GetString("tether_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст збережено.
        /// </summary>
        internal static string TextSaved {
            get {
                return ResourceManager.GetString("TextSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст занадто короткий. Це точно тести?.
        /// </summary>
        internal static string TextToShort {
            get {
                return ResourceManager.GetString("TextToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секунду, рендеримо...
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
    }
}
