//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AppStartingPrealoader {
            get {
                object obj = ResourceManager.GetObject("AppStartingPrealoader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можливо знайти шлях до файлу. Спочатку відкрийте файл з завданням.
        /// </summary>
        internal static string CantFindDefPath {
            get {
                return ResourceManager.GetString("CantFindDefPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можливо знайти шлях до файлу. Спочатку відкрийте файл з завданням. Після цього можна зберегти файл з іншою назвою.
        /// </summary>
        internal static string CantFindDefPath2 {
            get {
                return ResourceManager.GetString("CantFindDefPath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спочатку виберіть файл і згенеруйте його!.
        /// </summary>
        internal static string ChouseFileFst {
            get {
                return ResourceManager.GetString("ChouseFileFst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування завантажені.
        /// </summary>
        internal static string DefLoaded {
            get {
                return ResourceManager.GetString("DefLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function ()
        ///{    
        ///    var tour = new Shepherd.Tour({
        ///            defaults: {
        ///                classes: &apos;shepherd-theme-arrows&apos;
        ///            }
        ///        });
        ///
        ///
        ///        tour.addStep(&apos;st-1&apos;, {
        ///            title: &apos;Hi!&apos;,
        ///            text: &apos;I will show you some simple steps in generating content&apos;,
        ///
        ///            buttons: [{
        ///                text: &apos;Next&apos;,
        ///                action: tour.next
        ///            }]
        ///        });
        ///        tour.addStep(&apos;st-4&apos;, {
        ///            title: &apos;Settings&apos;,
        ///            text: &apos;You ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string easy_start_tour_EN {
            get {
                return ResourceManager.GetString("easy_start_tour_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function ()
        ///{    
        ///    var tour = new Shepherd.Tour({
        ///            defaults: {
        ///                classes: &apos;shepherd-theme-arrows&apos;
        ///            }
        ///        });
        ///
        ///
        ///        tour.addStep(&apos;st-1&apos;, {
        ///            title: &apos;Привіт!&apos;,
        ///            text: &apos;Я покажу Вам декілька простих кроків з генератором&apos;,
        ///
        ///            buttons: [{
        ///                text: &apos;Продовжимо?&apos;,
        ///                action: tour.next
        ///            }]
        ///        });
        ///        tour.addStep(&apos;st-4&apos;, {
        ///            title: &apos;Налаштування&apos;,
        ///            tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string easy_start_tour_UA {
            get {
                return ResourceManager.GetString("easy_start_tour_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon1 {
            get {
                object obj = ResourceManager.GetObject("favicon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генеруємо... Зачекайте, будь ласка.
        /// </summary>
        internal static string Gen {
            get {
                return ResourceManager.GetString("Gen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML не було збережено автоматично. Виберіть файл з завданням або виберіть папку для &quot;index.html&quot;.
        /// </summary>
        internal static string HtmlNotAutoSaved {
            get {
                return ResourceManager.GetString("HtmlNotAutoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML збережено.
        /// </summary>
        internal static string HtmlSaved {
            get {
                return ResourceManager.GetString("HtmlSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; src=&quot;./content/favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///
        ///    &lt;link href=&quot;./content/css/shepherd-theme-arrows.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;./content/css/style.css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;./content/css/bootstrap.min.css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;./content/css/tether.min.css&quot;&gt;
        ///    &lt;link rel=&quot;style [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(&apos;#loc-file-drop&apos;).text(&apos;Файл&apos;);
        ///$(&apos;#loc-prefs-drop&apos;).text(&apos;Налаштування&apos;);
        ///$(&apos;#loc-about&apos;).text(&apos;Про програму&apos;);
        ///$(&apos;#loc-open&apos;).text(&apos;Відкрити файл&apos;);
        ///$(&apos;#loc-txt-s&apos;).text(&apos;Зберегти&apos;);
        ///$(&apos;#loc-txt-ss&apos;).text(&apos;Зберегти як&apos;);
        ///$(&apos;#loc-html-s&apos;).text(&apos;Зберегти&apos;);
        ///$(&apos;#loc-html-ss&apos;).text(&apos;Зберегти як&apos;);
        ///$(&apos;#loc-exit&apos;).text(&apos;Вихід&apos;);
        ///$(&apos;#loc-prefs&apos;).text(&apos;Вигляд&apos;);
        ///$(&apos;#loc-sett&apos;).text(&apos;Налаштування&apos;);
        ///$(&apos;#loc-gend&apos;).text(&apos;Згенероване&apos;);
        ///$(&apos;#loc-txt-from&apos;).text(&apos;Текст з файлу&apos;);
        ///$(&apos;#loc-gen&apos;).text(&apos;Ген [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string localize_UA {
            get {
                return ResourceManager.GetString("localize_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст збережено.
        /// </summary>
        internal static string TextSaved {
            get {
                return ResourceManager.GetString("TextSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст занадто короткий. Це точно тести?.
        /// </summary>
        internal static string TextToShort {
            get {
                return ResourceManager.GetString("TextToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секунду, рендеримо...
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
    }
}
